$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
dictionaries: []
dictionaryDefinitions: []
enableFiletypes:
  - lua
  - json
  - makefile
  - markdown
  - plaintext
  - shellscript
  - text
ignorePaths:
  - .gitignore
  - cspell.config.yaml
ignoreWords: []
import:
  - ../cspell.config.yaml
version: "0.2"
words:
  - augroup
  - autocmd
  - autocmds
  - autocommand
  - Autocommands
  - Autoinstall
  - autopairs
  - breakindent
  - bufnr
  - changedelete
  - checkhealth
  - clangd
  - colorschemes
  - ction
  - cursorline
  - dapui
  - devicons
  - diffthis
  - earch
  - echasnovski
  - eclaration
  - eferences
  - efinition
  - elete
  - eleted
  - eovim
  - eplace
  - eset
  - esume
  - expandtab
  - eymaps
  - folke
  - getchar
  - gitsigns
  - gopls
  - hange
  - hjkl
  - hlsearch
  - iagnostics
  - ignorecase
  - iles
  - inccommand
  - inko
  - isort
  - isually
  - jsonlint
  - jsregexp
  - kanagawa
  - Keybinds
  - keymap
  - Keymaps
  - kondo
  - lazydev
  - lazypath
  - lazyrepo
  - leoluz
  - listchars
  - localappdata
  - lspconfig
  - luajit
  - luasnip
  - lukas
  - luvit
  - mapleader
  - maplocalleader
  - mfussenegger
  - modeline
  - mplementation
  - Munif
  - neotest
  - Neotree
  - neovim
  - nner
  - nohlsearch
  - norl
  - noto
  - nside
  - numhl
  - nvim
  - oggle
  - oldfiles
  - ormat
  - premade
  - pyright
  - rafamadriz
  - rcarriga
  - rebelot
  - reineke
  - relativenumber
  - reqs
  - saghen
  - saiw
  - scrolloff
  - setloclist
  - shiftwidth
  - showmode
  - signcolumn
  - smartcase
  - splitbelow
  - statusline
  - stdpath
  - stevearc
  - tage
  - Tanjim
  - termguicolors
  - texthl
  - textobjects
  - tflint
  - timeoutlen
  - topdelete
  - tpope
  - uffer
  - uickfix
  - undofile
  - unnamedplus
  - uote
  - updatetime
  - urround
  - verstr
  - virtualedit
  - vimdoc
  - williamboman
  - winblend
  - wincmd
  - windwp
  - xclip
  - xsel
  - yinq
